### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Noted#12]
According to @kasperwelner, filtering notifications doesn't work as it should. Kasper's [`filter` branch](https://github.com/nodes-ios/Noted/tree/filter) has a test that fails and it should pass. We should look into this soon and get it fixed.

**Comment by mariusc** [comment]
Ok, I looked a bit at this and the filtering feature seems a bit unfinished. I'm not very familiar with the project, so I might not see the bigger picture, but here are some remarks/questions:
- The `TestFilter` in @kasperwelner's test should return `true`. Since [it's `false`](https://github.com/nodes-ios/Noted/blob/filter/NotedTests/Test%20Objects/TestFilter.swift#L14), it will act like the `PassthroughNoteFilter` and it won't be filtered. However, the filtering is broken anyway, changing the return to `true` also doesn't help pass the test.
- I added a breakpoint [where the filtering is done](https://github.com/nodes-ios/Noted/blob/filter/Noted/Classes/Noted.swift#L46). The issue is that the observer's filter is a `PassthroughNoteFilter`. And that happens because when an observer is added, [the filter that's sent as parameter isn't used](https://github.com/nodes-ios/Noted/blob/filter/Noted/Classes/Noted.swift#L29).
- A solution would be to add the filter to the observer inside that function. But we can't do that currently, because [the `noteFilter` in `Observer` is read only](https://github.com/nodes-ios/Noted/blob/filter/Noted/Classes/NoteObserver.swift). Is there any reason why `noteFilter` is read only on `Observer`?
- If the `noteFilter` is a property on the `Observer`, [what's the point in `add(observer:filter)` to take them both as parameters](https://github.com/nodes-ios/Noted/blob/filter/Noted/Classes/Noted.swift#L29)? The developers can just set the filter on the observer and add the observer (without sending the filter as a parameter to the `add(observer)` function.

I hope what I wrote is clear; if it's not, ask.
@kasperwelner , @nickskull Let me know what you think

**Comment by dominik-hadl** [comment]
Ha! 

1) This is correct, the test would have always failed with `false`.
2) Seems like we forgot to remove the filter parameter in the `add(observer:)` function when we were refactoring the filtering functionality. 
3) Yes, reason for this is that it's a protocol and the filter is meant to be overridden in case you don't want to use the default passthrough filter.
4) Same answer as point 2 :D

However, the filtering works fine, it was just the test that didn't follow the docs in the README :P 
I've just made two commits fixing both the test and the extraneous parameter in the filter branch.

**Comment by mariusc** [comment]
Ok, makes sense. I guess both Kasper and I should've RTFM 😅.
