### ISSUE TITLE
Set up HoundCI

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Noted#16]

**Comment by mariusc** [comment]
Looks like HoundCI runs even without specifying a custom SwiftLint configuration. 
![image](https://cloud.githubusercontent.com/assets/844175/22365012/836684f4-e475-11e6-9bdc-03fb3ee475ba.png)
We need to figure out if we want the default settings (whichever they are, I can't figure out), or if we want to setup something more custom
